[package]
name = "misfortunate"
description = "Perverse implementations of safe Rust traits"
license = "LGPL-2.0"
repository = "https://github.com/tialaramex/misfortunate/"
version = "0.2.0"
authors = ["Nick Lamb <git@tree.tlrmx.org>"]
edition = "2018"

[dependencies]
