[package]
name = "misfortunate"
version = "0.1.0"
authors = ["Nick Lamb <git@tree.tlrmx.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
